#!/usr/bin/env python
"""Audit submission-PDF freshness against the current ``paper/main.tex``.

The other paper-shape audits (``audit_paper_submission_shape.py``,
``audit_submission_pdf_shape.py``, ``audit_iclr_submission_readiness.py``)
verify the content of whatever PDFs they find on disk. None of them notice
when ``paper/main.tex`` has been edited after the PDFs were last rebuilt.
This audit closes that gap: it fails when any submission PDF is older than
``paper/main.tex``, so a stale PDF cannot be silently uploaded.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_JSON = ROOT / "runs" / "paper_pdf_freshness_audit.json"
DEFAULT_OUT_MD = ROOT / "docs" / "paper_pdf_freshness_audit.md"

TRACKED_PDFS = [
    "paper/main.pdf",
    "paper/main_submission.pdf",
    "paper/iclr_submission.pdf",
    "paper/neurips_submission.pdf",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--paper-tex", type=Path, default=ROOT / "paper" / "main.tex")
    parser.add_argument("--out-json", type=Path, default=DEFAULT_OUT_JSON)
    parser.add_argument("--out-md", type=Path, default=DEFAULT_OUT_MD)
    return parser.parse_args()


def relpath(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def build_payload(paper_tex: Path) -> dict[str, Any]:
    if not paper_tex.exists():
        return {
            "paper_pdf_freshness_audit_ready": False,
            "paper_tex": relpath(paper_tex),
            "paper_tex_mtime": None,
            "pdfs": [],
            "risk_flags": ["paper_tex_missing"],
        }
    paper_tex_mtime = paper_tex.stat().st_mtime
    pdfs: list[dict[str, Any]] = []
    risk_flags: list[str] = []
    for rel in TRACKED_PDFS:
        pdf_path = ROOT / rel
        if not pdf_path.exists():
            pdfs.append(
                {
                    "path": rel,
                    "exists": False,
                    "pdf_mtime": None,
                    "stale_vs_source": None,
                }
            )
            risk_flags.append(f"missing_pdf:{rel}")
            continue
        pdf_mtime = pdf_path.stat().st_mtime
        stale = pdf_mtime < paper_tex_mtime
        pdfs.append(
            {
                "path": rel,
                "exists": True,
                "pdf_mtime": pdf_mtime,
                "stale_vs_source": stale,
            }
        )
        if stale:
            risk_flags.append(f"stale_pdf:{rel}")
    return {
        "paper_pdf_freshness_audit_ready": not risk_flags,
        "paper_tex": relpath(paper_tex),
        "paper_tex_mtime": paper_tex_mtime,
        "pdfs": pdfs,
        "risk_flags": risk_flags,
    }


def write_json(payload: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_markdown(payload: dict[str, Any], path: Path) -> None:
    ready = "ready" if payload["paper_pdf_freshness_audit_ready"] else "not ready"
    lines = [
        "# Paper PDF Freshness Audit",
        "",
        "This audit fails when any submission PDF is older than",
        "`paper/main.tex`. Together with `audit_paper_submission_shape.py`",
        "and `audit_submission_pdf_shape.py`, it closes the gap between the",
        "source manuscript and the artifact a reviewer would download.",
        "",
        f"Current status: {ready}.",
        f"`paper/main.tex` modification time: `{payload['paper_tex_mtime']}`.",
        "",
        "| PDF | Exists | mtime | Stale vs source |",
        "| --- | --- | --- | --- |",
    ]
    for entry in payload["pdfs"]:
        lines.append(
            "| {path} | {exists} | {mtime} | {stale} |".format(
                path=entry["path"],
                exists=entry["exists"],
                mtime=entry["pdf_mtime"],
                stale=entry["stale_vs_source"],
            )
        )
    lines.extend(
        [
            "",
            "## Risk Flags",
            "",
        ]
    )
    if payload["risk_flags"]:
        for flag in payload["risk_flags"]:
            lines.append(f"- {flag}")
    else:
        lines.append("- none")
    lines.extend(
        [
            "",
            "This file is generated by `scripts/audit_paper_pdf_freshness.py`.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    payload = build_payload(args.paper_tex)
    write_json(payload, args.out_json)
    write_markdown(payload, args.out_md)
    print(
        json.dumps(
            {
                "paper_pdf_freshness_audit_ready": payload[
                    "paper_pdf_freshness_audit_ready"
                ],
                "risk_flags": payload["risk_flags"],
                "out_json": str(args.out_json),
                "out_md": str(args.out_md),
            }
        )
    )


if __name__ == "__main__":
    main()
