#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from audit_paper_submission_shape import ROOT, pdf_page_count


DEFAULT_OUT_JSON = ROOT / "runs" / "submission_pdf_shape_audit.json"
DEFAULT_OUT_MD = ROOT / "docs" / "submission_pdf_shape_audit.md"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--submission-pdf", type=Path, default=ROOT / "paper" / "main_submission.pdf")
    # 10 main-text pages (cf. MAIN_TEXT_PAGE_BUDGET in
    # verify_source_repository_snapshot.py) + 1 page of references = 11 total
    # PDF pages. This audit measures raw PDF page count rather than
    # content-before-references; the canonical content-budget check lives in
    # verify_source_repository_snapshot.py / audit_iclr_submission_readiness.py.
    parser.add_argument("--max-pages", type=int, default=11)
    parser.add_argument("--out-json", type=Path, default=DEFAULT_OUT_JSON)
    parser.add_argument("--out-md", type=Path, default=DEFAULT_OUT_MD)
    return parser.parse_args()


def build_audit(submission_pdf: Path, max_pages: int) -> dict[str, Any]:
    page_count = pdf_page_count(submission_pdf)
    exists = submission_pdf.exists()
    size_bytes = submission_pdf.stat().st_size if exists else 0
    risk_flags = []
    if not exists:
        risk_flags.append("missing_submission_pdf")
    if page_count is None:
        risk_flags.append("submission_pdf_page_count_unavailable")
    elif page_count > max_pages:
        risk_flags.append("submission_pdf_over_page_budget")
    if size_bytes < 100_000:
        risk_flags.append("submission_pdf_too_small")
    return {
        "submission_pdf": submission_pdf.relative_to(ROOT).as_posix(),
        "pdf_page_count": page_count,
        "max_pages": max_pages,
        "size_bytes": size_bytes,
        "risk_flags": risk_flags,
        "submission_pdf_ready": not risk_flags,
        "interpretation": (
            "This audit checks the main-only submission PDF, excluding the "
            "appendix/generated evidence tables that remain in paper/main.pdf."
        ),
    }


def write_json(payload: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_markdown(payload: dict[str, Any], path: Path) -> None:
    ready = "ready" if payload["submission_pdf_ready"] else "not ready"
    lines = [
        "# Submission PDF Shape Audit",
        "",
        "This generated audit checks the main-only submission PDF produced by",
        "`make paper-submission-check`. The appendix-inclusive reproducibility PDF",
        "remains `paper/main.pdf`; this audit is for the venue-facing main paper.",
        "",
        f"Current status: {ready}.",
        "",
        "## Metrics",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| Submission PDF | `{payload['submission_pdf']}` |",
        f"| PDF pages | {payload['pdf_page_count']} |",
        f"| Page budget | {payload['max_pages']} |",
        f"| Size bytes | {payload['size_bytes']} |",
        "",
        "## Risk Flags",
        "",
    ]
    if payload["risk_flags"]:
        for flag in payload["risk_flags"]:
            lines.append(f"- {flag}")
    else:
        lines.append("- none")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            payload["interpretation"],
            "",
            "This file is generated by `scripts/audit_submission_pdf_shape.py`.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    payload = build_audit(args.submission_pdf, args.max_pages)
    write_json(payload, args.out_json)
    write_markdown(payload, args.out_md)
    print(
        json.dumps(
            {
                "submission_pdf_ready": payload["submission_pdf_ready"],
                "pdf_page_count": payload["pdf_page_count"],
                "risk_flags": payload["risk_flags"],
                "out_json": str(args.out_json),
                "out_md": str(args.out_md),
            }
        )
    )


if __name__ == "__main__":
    main()
