#!/usr/bin/env python
from __future__ import annotations

import argparse
import csv
import json
import math
import re
from pathlib import Path


FIELDS = [
    "label",
    "num_runs",
    "dense_acc",
    "imp_acc",
    "sparsity",
    "posterior",
    "random",
    "posterior_minus_random",
    "chain_start",
    "posterior_minus_chain_start",
    "posterior_to_chain_start",
    "dense_magnitude",
    "rewind_magnitude",
    "dense_minus_posterior",
    "snip",
    "synflow",
    "gate1_passed",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary",
        action="append",
        required=True,
        help="Path to a sparsity-sweep summary JSON. May be passed multiple times.",
    )
    parser.add_argument("--out-csv", type=Path, required=True)
    parser.add_argument("--out-md", type=Path, required=True)
    return parser.parse_args()


def mean(payload: dict, field: str) -> float:
    value = payload["summary"].get(field, {}).get("mean", math.nan)
    return float(value)


def label_from_path(path: Path) -> str:
    name = path.name.removesuffix("_summary.json")
    match = re.search(r"(r\d+_p[0-9p]+)$", name)
    return match.group(1) if match else name


def load_eval(path: Path) -> bool | str:
    eval_path = path.with_name(path.name.replace("_summary.json", "_gate1_eval.json"))
    if not eval_path.exists():
        return ""
    with eval_path.open(encoding="utf-8") as f:
        return bool(json.load(f)["gate1_passed"])


def load_row(path: Path) -> dict[str, float | int | str | bool]:
    with path.open(encoding="utf-8") as f:
        payload = json.load(f)

    posterior = mean(payload, "posterior_jaccard_mean")
    random = mean(payload, "random_jaccard_mean")
    chain_start = mean(payload, "chain_start_magnitude_to_imp_jaccard_mean")
    dense = mean(payload, "dense_magnitude_to_imp_jaccard")
    return {
        "label": label_from_path(path),
        "num_runs": int(payload["num_runs"]),
        "dense_acc": mean(payload, "dense_accuracy"),
        "imp_acc": mean(payload, "imp_accuracy"),
        "sparsity": mean(payload, "imp_sparsity"),
        "posterior": posterior,
        "random": random,
        "posterior_minus_random": posterior - random,
        "chain_start": chain_start,
        "posterior_minus_chain_start": posterior - chain_start,
        "posterior_to_chain_start": mean(
            payload, "posterior_to_chain_start_magnitude_jaccard_mean"
        ),
        "dense_magnitude": dense,
        "rewind_magnitude": mean(payload, "rewind_magnitude_to_imp_jaccard"),
        "dense_minus_posterior": dense - posterior,
        "snip": mean(payload, "snip_to_imp_jaccard"),
        "synflow": mean(payload, "synflow_to_imp_jaccard"),
        "gate1_passed": load_eval(path),
    }


def fmt(value: float | int | str | bool) -> str:
    if isinstance(value, bool):
        return "pass" if value else "fail"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if math.isnan(value):
            return "n/a"
        return f"{value:.4f}"
    return str(value)


def write_markdown(rows: list[dict[str, float | int | str | bool]], path: Path) -> None:
    headers = [
        "Config",
        "Runs",
        "Dense Acc",
        "IMP Acc",
        "Sparsity",
        "Posterior",
        "Random",
        "Post-Rand",
        "Chain Start",
        "Post-Chain Start",
        "Post-Chain",
        "Dense Mag",
        "Rewind Mag",
        "Dense-Post",
        "SNIP",
        "SynFlow",
        "Gate1",
    ]
    lines = [
        "# Sparsity Sweep Snapshot",
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] + ["---:"] * (len(headers) - 1)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(fmt(row[field]) for field in FIELDS) + " |")
    lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "A posterior-mode explanation requires a positive Post-Chain Start",
            "gap, low Post-Chain overlap, and a small Dense-Post gap. Runs below",
            "the planned seed count should be treated as incomplete.",
            "",
            "This file is generated by `scripts/build_sparsity_sweep_table.py`.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows = [load_row(Path(path)) for path in args.summary]
    rows.sort(key=lambda row: float(row["sparsity"]))

    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    with args.out_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    write_markdown(rows, args.out_md)
    print(f"wrote {args.out_csv}")
    print(f"wrote {args.out_md}")


if __name__ == "__main__":
    main()
